### ISSUE TITLE
Including both GitLens and Git Blame?

### ISSUE THREAD

**Issue by eamodio** [DonJayamanne/git-extension-pack#1]
I truly mean no disrespect to Git Blame, but having both GitLens and Git Blame in this pack seems less than ideal. Mainly because having both active will double the overhead (since both work on the active file/selection -- not just a command execution) and will double the info on the status bar -- which doesn't feel to me like a good thing for someone installing this. Also GitLens provides (as far as I'm aware) all of the functionality of Git Blame.

At the same time, thank you for including GitLens in your pack :)

**Comment by DonJayamanne** [comment]
You're absolutely right, will fix this ASAP.
