### ISSUE TITLE
Intellisense affected

### ISSUE THREAD

**Issue by Marriaga** [DonJayamanne/git-extension-pack#7]
My Intellisense in Python is significantly affected by this extensions making it extremely slow or even completely non-functional.

I was not able to reproduce the issue consistently. The only thing that was consistent was that disabling the pack fixed the issue. But turning the pack (or individual extensions) on did not necessarily reproduce the problem immediately.

**Comment by DonJayamanne** [comment]
This extension doesn't have the ability to impact intellisense, hence closing this issue.
